name: Extraordinary Love Path
favicon: null
layout_spectrum: 0.04530449560843408
typography_spectrum: 0.9792701818514615
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.09101367206312716
  lightness: 0.17851071152836084
  saturation: 0.706814851379022
  rhythmicContrast: 0.4494450876954943
purpose: []
